task: 'fashion'
subject: 'karina_m377'
experiment: 'smpl_init_texture'
#resume: True
pretrained: ''
load_net: '' # the name of saved model when resuming the training

##############################################3
## Data Configuration

train:
  skip: 1
  dataset_module: 'core.data.elicit.init'
  maxiter: 15000
  save_model_interval: 5000
  dataset: 'fashion_karina_m377_train'

progress:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_377_test'

movement:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_377_test'

freeview:
  dataset_module: 'core.data.elicit.freeview'
  dataset: 'zju_377_test'

tpose:
  dataset_module: 'core.data.elicit.tpose'
  dataset: 'zju_377_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
ignore_non_rigid_motions: True