task: 'zju_mocap'
subject: 'p393_smpl'
experiment: 'smpl_init_texture'
#resume: True
pretrained: ''
load_net: latest # the name of saved model when resuming the training

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.elicit.init'
  maxiter: 15000
  dataset: 'zju_393_smpl_train'

progress:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_393_test'

movement:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_393_test'

freeview:
  dataset_module: 'core.data.elicit.freeview'
  dataset: 'zju_393_test'

tpose:
  dataset_module: 'core.data.elicit.tpose'
  dataset: 'zju_393_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
ignore_non_rigid_motions: True