task: 'zju_mocap'
subject: 'p386_smpl'
experiment: 'smpl_init_new_texture_v2'
resume: True
pretrained: ''
load_net: latest # the name of saved model when resuming the training

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.elicit.init'
  maxiter: 15000
  dataset: 'zju_386_smpl_train'
  repeat_first_and_last: 50

progress:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_386_test'

movement:
  dataset_module: 'core.data.elicit.init'
  dataset: 'zju_386_test'

freeview:
  dataset_module: 'core.data.elicit.freeview'
  dataset: 'zju_386_test'

tpose:
  dataset_module: 'core.data.elicit.tpose'
  dataset: 'zju_386_test'

bgcolor: [0., 0., 0.]
resize_img_scale: 0.5
ignore_non_rigid_motions: True